### ISSUE TITLE
一両編成の列車が他の列車に干渉する

### ISSUE THREAD

**Issue by kuromi-krm** [TCMB-Project/TCMB#3]
開発お疲れ様です。
使用バージョンはTCMBver1.2.2です。
表題の通り、一両編成(car1のみ)の列車を召喚したときに、先に召喚した車両の扉などが動かなくなる、また後に召喚した方に連動するという問題です。
ソースを見たところ、engine.jsのLine47~51、getEntitiesのqueryにて最も近いボディーを2つ取得しているためと推定されます。
maxDistanceを入れることで回避できるかと思います。
ご確認お願いいします。

**Comment by gensokyo-kenken** [comment]
[08f8d9c](https://github.com/TCMB-Project/TCMB/commit/08f8d9c3f0fc8e49e062d363f58b3c2241ea5bab)でmaxDistanceを入れました。

**Comment by gensokyo-kenken** [comment]
[v1.2.3](https://github.com/TCMB-Project/TCMB/releases/tag/v1.2.3)で修正されました。
