### ISSUE TITLE
[BUG] TCMB controller doesn't work

### ISSUE THREAD

**Issue by breakersun** [TCMB-Project/TCMB#4]
**バグの内容の説明**
Can't control the train, can't accelerate, can't control doors, can't kill the train

**再現手順**
バグを再現する手順:
1. import TCMB plugin
2. create my own train and import
3. spawn a train from nature->spawn_egg
4. use controller accelerate/door control to control the door, but not responding at all

**期待する動作**

**スクリーンショット**
スクリーンショットがある場合は、問題の説明に役立つスクリーンショットを追加してください。

**実行環境:** 
 - 端末: Android 11
 - Minecraftバージョン: 1.20.81
 - TCMBバージョン: 1.2.3

**その他の情報**
その他、このバグについて何かあれば、ここに書き加えてください。

**Comment by gensokyo-kenken** [comment]
Due to Minecraft specifications, you must hold the item in the air while holding it.
To work around this, use a spawn egg-style control item that can be retrieved from the "Nature" column.

Minecraftの仕様上、アイテムを持ったまま空中を長押しする必要があります。
これを回避するには、「Nature」欄から取り出せるスポーンエッグ式の操作アイテムを使用してください。

**Comment by breakersun** [comment]
Thank you for your help. 
Now I can use below items to control the train by holding the corresponding item in the air for a while:
- open/close door with sound effect(which is pretty cool)
- delete car

But I still can't control Acceleration(P) and Coasting(N) using the same method: the train/car doesn't move at all, neither make any sound.
Any suggestions?

**Comment by breakersun** [comment]
No matter how long I press and hold "P" item in the air, the train control pannel always looks like this, and it's not moving at all:
![image](https://github.com/TCMB-Project/TCMB/assets/6301217/b2b1182d-1244-4b0d-a712-4e499503a5f4)

**Comment by breakersun** [comment]
I searched around the code base, this is the code to execute power/breaker/emergency-break, right?

```js
                case "notchSignal":
                    train = world.getEntity(evdata.entity.id);
                    if(typeof train != "undefined" && train.typeId == "tcmb:tcmb_car"){
                        if(!train.hasTag("voltage_0")){
                            if(!(train.hasTag('eb') && evdata.status["operation"] == "break") && !(train.hasTag('p4') && evdata.status["operation"] == "power") && !(train.hasTag("n") && evdata.status["operation"] == "neutral") && !(train.hasTag('eb') && evdata.status['operation'] == 'eb')){
                                train.runCommandAsync("playsound notch @a[r=25]");
                                if(speedObject.getScore(train) == 0 && ((evdata.status["operation"] == "neutral") || (train.hasTag('b1') && evdata.status['operation'] == 'power'))) train.runCommandAsync("playsound break_remission @a[r=100]");
                                let event_report = new Event('notch', evdata.status, train, player);
                                event_report.reply();
                            }
                            if(evdata.status["operation"] != "eb"){
                                train.runCommandAsync("function notch_"+evdata.status["operation"]);
                            }else{
                                train.runCommandAsync("function eb");
                            }
                            if(train.hasTag("tc_parent") || train.hasTag("tc_child")) train.runCommandAsync("function tc_notch_"+evdata.status["operation"]);
                        }
                    }
                break;

```

**Comment by breakersun** [comment]
I just figured out how the "P" works: I should 
- use "P" to hit the control panel of the train, it will level up the engine
- and hold "B" in the air and hold it for a few seconds, it will brake the train

Looks like a little bit intuitive for me. Anyway it works, thank you.
